"""Stage 4 — lint + index maintenance (v5).

`lint(vault)` surfaces structural issues for v5:

* **dead_links** — `[[X]]` references where X.md is missing (narrative or note)

`update_index(vault)` regenerates `index.md` from scratch.

v5 paradigm (2026-04-24) simplifications:
- `orphans` / `sparse` concept metrics removed (concepts/ 廃止)
- Only narrative + source + note kinds exist
"""
from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone
from typing import Any

from pillars import compute_pillars
from vault import PAGE_KINDS, Vault, parse_wikilinks

_ALL_KINDS = PAGE_KINDS  # ("narrative", "source", "note")


def _all_slugs(vault: Vault) -> set[str]:
    out: set[str] = set()
    for kind in _ALL_KINDS:
        out.update(vault.list_pages(kind))
    return out


def _collect_outbound(vault: Vault) -> dict[tuple[str, str], list[str]]:
    """Return {(kind, slug): [referenced_slugs, ...]}."""
    out: dict[tuple[str, str], list[str]] = {}
    for kind in _ALL_KINDS:
        for slug in vault.list_pages(kind):
            if slug.startswith("_"):
                continue
            page = vault.read(kind, slug)
            if page is None:
                continue
            refs = [target for target, _display in parse_wikilinks(page.body)]
            out[(kind, slug)] = refs
    return out


def lint(vault: Vault) -> dict[str, Any]:
    known_slugs = _all_slugs(vault)
    outbound = _collect_outbound(vault)

    inbound_counts: Counter[str] = Counter()
    dead_links: list[dict[str, str]] = []
    for (kind, slug), refs in outbound.items():
        for target in refs:
            # `[[slug#heading]]` links resolve against the bare page slug;
            # strip the anchor before existence check. Pure `#anchor`
            # (same-page) links have an empty base and are not dead.
            base = target.split("#", 1)[0]
            if not base:
                continue
            inbound_counts[base] += 1
            if base not in known_slugs:
                dead_links.append({"from_kind": kind, "from_slug": slug, "to": target})

    suggestions: list[str] = []
    if dead_links:
        suggestions.append(
            "Dead wikilinks point at missing pages — create a note/<slug>.md"
            " if the concept is worth externalizing, or ignore if leaving"
            " the link as an Obsidian unresolved node is acceptable."
        )

    return {
        "dead_links": sorted(dead_links, key=lambda d: (d["from_kind"], d["from_slug"], d["to"])),
        "stats": {
            "narratives": len([s for s in vault.list_pages("narrative") if not s.startswith("_")]),
            "sources": len(vault.list_pages("source")),
            "notes": len(vault.list_pages("note")),
        },
        "suggestions": suggestions,
    }


def update_index(vault: Vault) -> None:
    """Regenerate index.md (header-guarded, safe to commit)."""
    lint_report = lint(vault)
    pillars = compute_pillars(vault, top_n=20)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines: list[str] = [
        "<!-- auto-generated by /wiki-lint. Do not edit manually. -->",
        "",
        "# Wiki Index",
        "",
        f"_Last updated: {now}_",
        "",
        "## 統計",
    ]
    for k, v in lint_report["stats"].items():
        lines.append(f"- {k}: {v}")

    if pillars.get("top"):
        lines += ["", "## 柱 (narrative 内 wikilink top 20)"]
        for rank, item in enumerate(pillars["top"], start=1):
            lines.append(f"{rank}. [[{item['slug']}]] — {item['backlinks']} backlinks")

    if lint_report["dead_links"]:
        lines += ["", "## Dead links (未解決 wikilink)"]
        for dl in lint_report["dead_links"][:50]:
            lines.append(f"- [[{dl['to']}]] ← {dl['from_kind']}/{dl['from_slug']}")

    (vault.root / "index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
